language: node_js
node_js:
- node
install:
- npm install -g mocha
- npm install chai
- npm install chai-http
- npm install express
deploy:
  provider: heroku
  app: heroku-calc-app
  on:
    all_branches: true
  api_key:
    secure: I9GPnpTfvAaFMsMp+amwMF1ty0MDJxFtWMyP5G7bMnroWt26iTE9WNkLtkwsgu+TmDL9f41FSXA2G/m5kj4LRK9G94yvCfRQvweqOZwAqFtIZl5mG0UhC57j4bULfv513tfSCowBuWTDBY8KYi8WC+zxYMP/U5/VF2uyzuj9DCWj5yC7RrtDIV6/7Z42OXi/H8df9OJuECiASce874Au+uo6+cn/YpOqwOg3yvmPJFZ4GTyvsPoCCNbJNVHEHanAHlJDk+iEpD30KfYS597R2vWvqZlGwM01hi7Q4ypUF2yF6EA1NttobMd1kS4xX9blXYYjyZxz6EGSGxBiSn9yLx3WN62yswY+Nnkpc3r3yIaHVSMoQAmbrjxw5eiRqUfFZhdvw5w/2GLdbIm33B2MPuM/S7+HHDMrQiqjpYV0Bo3Bid5+sgAI3j3vDMa23EIvho7E/nYWrAoBEa5GajD+zMD2vS6ipY5zANJEzfqXLkVQsJ9ker3pQTdIJGpKkgMm1n3olcnYk3qHdBdynNdF/ndx7XCbyUOF6mk/E1mVu39PW/rQJ16oW1xyiahx4vvYYky4hKq1xTfLFNY2GlBBIzQ1JTpovUKVh8y7kiykwZ+WJ3fHNAm8Qc6mmfPZZOROS/5uG6iTsAXuEyWs4ZfCwSFDX+jXyxXpcdBJVuV8FfQ=
